import { createClient } from '@supabase/supabase-js'

export type EditorialArticle = { id:string; title:string; slug:string; excerpt:string|null; cover_image:string|null; published_at:string; views?:number; categories:{id?:string;name:string;slug:string;color?:string|null}|null; profiles:{username:string;avatar_url?:string|null}|null }
export type EditorialVideo = { id:string; title:string; description?:string|null; thumbnail?:string|null; platform?:string|null; video_id?:string|null; video_url?:string|null; category?:string|null; duration?:number|null; views?:number|null; published_at?:string|null }
export type AuthorProfile = { id:string; username:string; avatar_url?:string|null; bio?:string|null; author_signature?:string|null; specialties?:string[]|null; twitter_url?:string|null; instagram_url?:string|null; linkedin_url?:string|null }
export type { LiveNews } from '@/lib/live-news'
export { getLiveNews } from '@/lib/live-news'

const articleSelect='id,title,slug,excerpt,cover_image,published_at,views,categories(id,name,slug,color),profiles(username,avatar_url)'
function db(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;if(!url||!key)return null;return createClient(url,key,{auth:{persistSession:false}})}
const rows=(value:unknown)=>(Array.isArray(value)?value:[]) as unknown as EditorialArticle[]
export const authorSlug=(value:string)=>value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')
const decodeAuthor=(value:string)=>{try{return decodeURIComponent(value).trim()}catch{return value.trim()}}

export async function getCategoryArchive(slug:string){const client=db();if(!client)return {category:null,articles:[] as EditorialArticle[]};const [cat,res]=await Promise.all([client.from('categories').select('id,name,slug,color').eq('slug',slug).maybeSingle(),client.from('articles').select(articleSelect.replace('categories(', 'categories!inner(')).eq('status','published').eq('categories.slug',slug).order('published_at',{ascending:false}).limit(120)]);return {category:cat.data as {id:string;name:string;slug:string;color?:string|null}|null,articles:rows(res.data)}}
export async function getTagArchive(slug:string){const client=db();if(!client)return {tag:null,articles:[] as EditorialArticle[]};const res=await client.from('article_tags').select(`articles(${articleSelect}),tags!inner(id,name,slug)`).eq('tags.slug',slug);const data=Array.isArray(res.data)?res.data:[];return {tag:(data[0] as any)?.tags||null,articles:data.map((x:any)=>x.articles).filter(Boolean) as EditorialArticle[]}}
export async function getAuthorArchive(identifier:string){const client=db();if(!client)return {author:null,articles:[] as EditorialArticle[]};const decoded=decodeAuthor(identifier),wantedSlug=authorSlug(decoded);let profile=await client.from('profiles').select('*').ilike('username',decoded).maybeSingle();if(!profile.data){const candidates=await client.from('profiles').select('*').in('role',['author','admin']);const match=(candidates.data||[]).find((item:any)=>authorSlug(item.username||'')===wantedSlug);profile={...profile,data:match||null} as typeof profile}if(!profile.data)return {author:null,articles:[] as EditorialArticle[]};const res=await client.from('articles').select(articleSelect).eq('author_id',(profile.data as any).id).eq('status','published').order('published_at',{ascending:false});return {author:profile.data as AuthorProfile,articles:rows(res.data)}}
export async function searchEditorialArticles(term:string){const client=db();if(!client||!term.trim())return [];const safe=term.trim().replace(/[%_,]/g,' ');const res=await client.from('articles').select(articleSelect).eq('status','published').or(`title.ilike.%${safe}%,excerpt.ilike.%${safe}%,content.ilike.%${safe}%`).order('published_at',{ascending:false}).limit(60);return rows(res.data)}
export async function getEditorialVideos(){const client=db();if(!client)return [] as EditorialVideo[];const res=await client.from('videos').select('*').eq('is_published',true).order('published_at',{ascending:false}).limit(120);return (Array.isArray(res.data)?res.data:[]) as EditorialVideo[]}
