'use client'
/* eslint-disable react-hooks/set-state-in-effect */

import { FormEvent, useCallback, useEffect, useRef, useState } from 'react'
import { Camera, Check, Eye, ImagePlus, LoaderCircle, Radio, Square, Trash2, Upload, Video } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Textarea } from '@/components/ui/textarea'
import { Switch } from '@/components/ui/switch'
import { Badge } from '@/components/reui/badge'

type Client = ReturnType<typeof import('@/lib/supabase/client').createClient>
type Item = {id:string;title:string;caption:string;alt_text:string;media_type:'image'|'video';media_url:string;storage_path:string;location:string|null;captured_at:string;status:'draft'|'published'|'archived';featured:boolean;created_at:string}

const shell='border border-white/10 bg-[#0d0e0e] shadow-[inset_0_1px_0_rgba(255,255,255,.04)]'

export function AdminGalleryStudio({client,user}:{client:Client;user:{id:string}}) {
  const inputRef=useRef<HTMLInputElement>(null), videoRef=useRef<HTMLVideoElement>(null), streamRef=useRef<MediaStream|null>(null)
  const [items,setItems]=useState<Item[]>([]),[file,setFile]=useState<File|null>(null),[preview,setPreview]=useState(''),[camera,setCamera]=useState(false)
  const [title,setTitle]=useState(''),[caption,setCaption]=useState(''),[alt,setAlt]=useState(''),[location,setLocation]=useState(''),[publish,setPublish]=useState(true),[featured,setFeatured]=useState(false)
  const [busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState('')

  const load=useCallback(async()=>{const {data,error}=await client.from('gallery_items').select('*').order('captured_at',{ascending:false}).limit(150);if(error)setError(error.message);else setItems((data||[]) as Item[])},[client])
  useEffect(()=>{void load();const channel=client.channel('admin-gallery-live').on('postgres_changes',{event:'*',schema:'public',table:'gallery_items'},()=>void load()).subscribe();return()=>{void client.removeChannel(channel)}},[client,load])
  useEffect(()=>()=>{streamRef.current?.getTracks().forEach(track=>track.stop());if(preview)URL.revokeObjectURL(preview)},[preview])

  function choose(next:File|null){if(preview)URL.revokeObjectURL(preview);setFile(next);setPreview(next?URL.createObjectURL(next):'');if(next&&!title)setTitle(next.name.replace(/\.[^.]+$/,'').replaceAll(/[-_]+/g,' '))}
  async function startCamera(){setError('');if(!navigator.mediaDevices?.getUserMedia){inputRef.current?.click();return}try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1920},height:{ideal:1080}},audio:false});streamRef.current=stream;setCamera(true);requestAnimationFrame(()=>{if(videoRef.current){videoRef.current.srcObject=stream;void videoRef.current.play()}})}catch{setError('Fotocamera non disponibile: usa “Scatta o scegli” per aprire la fotocamera del telefono.');inputRef.current?.click()}}
  function stopCamera(){streamRef.current?.getTracks().forEach(track=>track.stop());streamRef.current=null;setCamera(false)}
  function snapshot(){const video=videoRef.current;if(!video?.videoWidth)return;const canvas=document.createElement('canvas');canvas.width=video.videoWidth;canvas.height=video.videoHeight;canvas.getContext('2d')?.drawImage(video,0,0);canvas.toBlob(blob=>{if(blob)choose(new File([blob],`stadio-${Date.now()}.jpg`,{type:'image/jpeg'}));stopCamera()},'image/jpeg',.92)}
  async function submit(event:FormEvent){event.preventDefault();if(!file||!title.trim())return setError('Aggiungi un file e un titolo.');setBusy(true);setError('');setNotice('');try{const ext=file.name.split('.').pop()?.toLowerCase()||'bin',kind=file.type.startsWith('video/')?'video':'image',path=`live/${new Date().toISOString().slice(0,10)}/${crypto.randomUUID()}.${ext}`;const {error:uploadError}=await client.storage.from('gallery-media').upload(path,file,{contentType:file.type,cacheControl:'31536000'});if(uploadError)throw uploadError;const {data:url}=client.storage.from('gallery-media').getPublicUrl(path);const now=new Date().toISOString();const {error:insertError}=await client.from('gallery_items').insert({author_id:user.id,media_type:kind,title:title.trim(),caption:caption.trim(),alt_text:alt.trim()||title.trim(),media_url:url.publicUrl,storage_path:path,location:location.trim()||null,captured_at:now,status:publish?'published':'draft',published_at:publish?now:null,featured});if(insertError){await client.storage.from('gallery-media').remove([path]);throw insertError}choose(null);setTitle('');setCaption('');setAlt('');setLocation('');setFeatured(false);setNotice(publish?'Pubblicato: la gallery si aggiorna in tempo reale.':'Salvato nelle bozze.');await load()}catch(e){setError(e instanceof Error?e.message:'Caricamento non riuscito.')}finally{setBusy(false)}}
  async function update(item:Item,values:Partial<Item>){const {error}=await client.from('gallery_items').update(values).eq('id',item.id);if(error)setError(error.message);else await load()}
  async function remove(item:Item){if(!confirm(`Eliminare “${item.title}” e il file originale?`))return;setError('');const {error}=await client.from('gallery_items').delete().eq('id',item.id);if(error)return setError(error.message);await client.storage.from('gallery-media').remove([item.storage_path]);await load()}

  return <div className="space-y-8 pb-24">
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1.25fr)_minmax(320px,.75fr)]">
      <Card className={`${shell} overflow-hidden rounded-[2rem] p-1.5`}><CardContent className="rounded-[calc(2rem-.375rem)] bg-black p-3 md:p-6">
        <div className="mb-5 flex flex-wrap items-start justify-between gap-4"><div><Badge variant="warning"><Radio className="size-3"/> Stadium capture</Badge><h2 className="mt-3 font-serif text-3xl">Dallo stadio alla gallery</h2><p className="mt-2 max-w-xl text-sm text-[#9a9a95]">Scatta, descrivi e pubblica foto o video senza uscire dalla control room.</p></div><span className="text-[10px] uppercase tracking-[.22em] text-[#bd9b61]">Live workflow</span></div>
        {camera?<div className="relative overflow-hidden rounded-[1.5rem] bg-black ring-1 ring-white/10"><video ref={videoRef} muted playsInline className="aspect-video w-full object-cover"/><div className="absolute inset-x-0 bottom-4 flex justify-center gap-3"><Button type="button" onClick={snapshot} className="size-14 rounded-full bg-[#d2b27d] text-black" aria-label="Scatta fotografia"><Camera/></Button><Button type="button" onClick={stopCamera} variant="outline" className="size-14 rounded-full" aria-label="Chiudi fotocamera"><Square/></Button></div></div>:preview?<div className="relative overflow-hidden rounded-[1.5rem] bg-black ring-1 ring-white/10">{file?.type.startsWith('video/')?<video src={preview} controls className="max-h-[56dvh] w-full object-contain"/>:<img src={preview} alt="Anteprima del file selezionato" className="max-h-[56dvh] w-full object-contain"/>}<Button type="button" variant="outline" className="absolute right-3 top-3 rounded-full" onClick={()=>choose(null)}>Cambia</Button></div>:<button type="button" onClick={()=>inputRef.current?.click()} className="group flex min-h-72 w-full flex-col items-center justify-center rounded-[1.5rem] bg-[#121313] px-6 text-center ring-1 ring-white/10 transition duration-700 ease-[cubic-bezier(.32,.72,0,1)] hover:bg-[#171716] focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#d2b27d]"><span className="grid size-16 place-items-center rounded-full bg-[#d2b27d] text-black transition duration-700 group-hover:scale-105"><ImagePlus/></span><b className="mt-5 text-lg">Scatta o scegli un contenuto</b><small className="mt-2 text-[#8d8d88]">JPG, PNG, WebP, MP4, WebM o MOV · massimo 100 MB</small></button>}
        <input ref={inputRef} className="sr-only" type="file" accept="image/*,video/*" capture="environment" onChange={e=>choose(e.target.files?.[0]||null)}/>
        {!camera&&<div className="mt-4 grid gap-3 sm:grid-cols-2"><Button type="button" size="lg" variant="outline" onClick={startCamera}><Camera/> Fotocamera live</Button><Button type="button" size="lg" variant="outline" onClick={()=>inputRef.current?.click()}><Upload/> Scatta o scegli</Button></div>}
      </CardContent></Card>
      <form onSubmit={submit} className={`${shell} rounded-[2rem] p-6 md:p-7`}><h2 className="font-serif text-2xl">Dettagli editoriali</h2><div className="mt-6 space-y-5"><div><Label htmlFor="gallery-title">Titolo</Label><Input id="gallery-title" maxLength={140} required value={title} onChange={e=>setTitle(e.target.value)}/></div><div><Label htmlFor="gallery-caption">Racconto</Label><Textarea id="gallery-caption" rows={5} value={caption} onChange={e=>setCaption(e.target.value)}/></div><div><Label htmlFor="gallery-alt">Testo alternativo</Label><Input id="gallery-alt" value={alt} onChange={e=>setAlt(e.target.value)} placeholder="Descrivi ciò che si vede"/></div><div><Label htmlFor="gallery-location">Luogo</Label><Input id="gallery-location" value={location} onChange={e=>setLocation(e.target.value)} placeholder="Allianz Stadium, Torino"/></div><div className="flex min-h-12 items-center justify-between"><Label htmlFor="gallery-publish">Pubblica subito</Label><Switch id="gallery-publish" checked={publish} onCheckedChange={setPublish}/></div><div className="flex min-h-12 items-center justify-between"><Label htmlFor="gallery-featured">In evidenza</Label><Switch id="gallery-featured" checked={featured} onCheckedChange={setFeatured}/></div></div>{error&&<p className="mt-5 text-sm text-red-400" role="alert">{error}</p>}{notice&&<p className="mt-5 text-sm text-emerald-300" role="status"><Check className="mr-2 inline size-4"/>{notice}</p>}<Button disabled={busy||!file} size="lg" className="mt-6 w-full rounded-full bg-[#d2b27d] text-black hover:bg-[#e4c992]">{busy?<LoaderCircle className="animate-spin"/>:<Upload/>}{busy?'Caricamento…':publish?'Pubblica ora':'Salva bozza'}</Button></form>
    </div>
    <section aria-labelledby="gallery-library-title"><div className="mb-5 flex items-end justify-between"><div><span className="text-[10px] uppercase tracking-[.22em] text-[#bd9b61]">Archivio live</span><h2 id="gallery-library-title" className="mt-2 font-serif text-3xl">Media pubblicati</h2></div><Badge variant="outline">{items.length} elementi</Badge></div><div className="grid gap-4 sm:grid-cols-2 2xl:grid-cols-3">{items.map(item=><Card key={item.id} className={`${shell} overflow-hidden rounded-[1.5rem] p-1.5`}><div className="relative aspect-[4/3] overflow-hidden rounded-[calc(1.5rem-.375rem)] bg-black">{item.media_type==='video'?<video src={item.media_url} muted playsInline preload="metadata" className="h-full w-full object-cover"/>:<img src={item.media_url} alt={item.alt_text} loading="lazy" className="h-full w-full object-cover"/>}<div className="absolute left-3 top-3 flex gap-2"><Badge variant={item.status==='published'?'success':'warning'}>{item.status==='published'?'Live':'Bozza'}</Badge>{item.media_type==='video'&&<Badge variant="outline"><Video className="size-3"/> Video</Badge>}</div></div><CardContent className="p-4"><h3 className="line-clamp-2 font-serif text-xl">{item.title}</h3><p className="mt-1 text-xs text-[#888]">{item.location||'Luogo non indicato'} · {new Date(item.captured_at).toLocaleString('it-IT')}</p><div className="mt-4 flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={()=>update(item,{status:item.status==='published'?'draft':'published',...(item.status!=='published'?{published_at:new Date().toISOString()}: {})})}>{item.status==='published'?<Eye/>:<Upload/>}{item.status==='published'?'Nascondi':'Pubblica'}</Button><Button size="sm" variant="outline" onClick={()=>update(item,{featured:!item.featured})}>{item.featured?'Rimuovi evidenza':'In evidenza'}</Button><Button size="icon-sm" variant="destructive" aria-label={`Elimina ${item.title}`} onClick={()=>remove(item)}><Trash2/></Button></div></CardContent></Card>)}{!items.length&&<div className={`${shell} col-span-full rounded-[2rem] px-6 py-20 text-center`}><Camera className="mx-auto text-[#bd9b61]"/><h3 className="mt-4 font-serif text-2xl">Il primo scatto parte da qui</h3><p className="mt-2 text-sm text-[#888]">Apri la fotocamera e pubblica il momento.</p></div>}</div></section>
  </div>
}
