'use client'

import Link from 'next/link'
import { authorSlug } from '@/lib/editorial-content'
import { FormEvent, useEffect, useMemo, useRef, useState } from 'react'
import type { Article, ArticleSidebar, ArticleTag } from '@/lib/content'
import type { Match, TransferRumor } from '@/lib/match-market-content'
import * as api from '@/lib/article-client'
import { COOKIE_CONSENT_EVENT, readCookieConsent } from '@/components/cookie-consent'

const REACTIONS = [{emoji:'ðŸ”¥',label:'Fuoco'},{emoji:'ðŸ‘',label:'Applauso'},{emoji:'â¤ï¸',label:'Cuore'},{emoji:'ðŸ˜®',label:'Wow'},{emoji:'ðŸ˜‚',label:'Divertente'}]
type Note = { id:string; highlight:string; note:string; createdAt:string }

function formatDate(value:string){return new Intl.DateTimeFormat('it-IT',{day:'numeric',month:'long',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(value))}
function readingMinutes(content=''){return Math.max(1,Math.ceil(content.replace(/<[^>]+>/g,' ').trim().split(/\s+/).filter(Boolean).length/220))}
function summary(content=''){const text=content.replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();const parts=text.replace(/([.!?])\s+/g,'$1|').split('|').filter(x=>x.length>30);return [parts[0],parts[Math.floor(parts.length/2)],parts.at(-1)].filter((x,i,a)=>x&&a.indexOf(x)===i).join(' ')}
function timeAgo(value:string){const mins=Math.floor((Date.now()-new Date(value).getTime())/60000);if(mins<1)return 'ora';if(mins<60)return `${mins} min fa`;const hours=Math.floor(mins/60);if(hours<24)return `${hours} ore fa`;return `${Math.floor(hours/24)} giorni fa`}
function tocLabel(el:Element){const clone=el.cloneNode(true) as HTMLElement;clone.querySelectorAll('table,figure,iframe,video,.table-scroll').forEach(node=>node.remove());const text=(clone.textContent||'').replace(/\s+/g,' ').trim();if(!text)return '';if(text.length<=56)return text;return `${text.slice(0,53).replace(/\s+\S*$/,'').trimEnd()}â€¦`}

export function ArticleExperience({article,related,tags,sidebar,nextMatch,rumor}:{article:Article;related:Article[];tags:ArticleTag[];sidebar:ArticleSidebar;nextMatch:Match|null;rumor:TransferRumor|null}){
  const root=useRef<HTMLElement>(null),prose=useRef<HTMLDivElement>(null)
  const [progress,setProgress]=useState(0),[views,setViews]=useState(Number(article.views)||0),[reader,setReader]=useState<api.Reader|null>(null)
  const [bookmarked,setBookmarked]=useState(false),[notice,setNotice]=useState(''),[tocOpen,setTocOpen]=useState(true),[summaryOpen,setSummaryOpen]=useState(false)
  const [headings,setHeadings]=useState<Array<{id:string;text:string;level:number}>>([]),[activeHeading,setActiveHeading]=useState('')
  const [comments,setComments]=useState<api.Comment[]>([]),[commentForm,setCommentForm]=useState({name:'',email:'',content:''}),[commentState,setCommentState]=useState('')
  const [reactionCounts,setReactionCounts]=useState<Record<string,number>>({}),[reaction,setReactionValue]=useState<string|null>(null)
  const [poll,setPoll]=useState<api.Poll|null>(null),[notes,setNotes]=useState<Note[]>([]),[noteOpen,setNoteOpen]=useState(false),[note,setNote]=useState(''),[highlight,setHighlight]=useState('')
  const [newsletter,setNewsletter]=useState(''),[newsletterState,setNewsletterState]=useState<'idle'|'sending'|'done'|'error'>('idle'),[newsletterMessage,setNewsletterMessage]=useState('')
  const minutes=useMemo(()=>readingMinutes(article.content||''),[article.content]),quick=useMemo(()=>summary(article.content||''),[article.content])

  useEffect(()=>{let live=true;api.getReader().then(async user=>{if(!live)return;setReader(user);if(user){setCommentForm(v=>({...v,name:v.name||user.name,email:user.email}));const state=await api.getReaderState(user.id).catch(()=>null);if(state){setBookmarked(state.bookmarks.some((x:any)=>x.id===article.id||x.articleId===article.id));const entry={articleId:article.id,id:article.id,slug:article.slug,title:article.title,categoryName:article.categories?.name||'',categorySlug:article.categories?.slug||'',readingMinutes:minutes,readAt:new Date().toISOString()};const history=[entry,...state.history.filter((x:any)=>x.id!==article.id&&x.articleId!==article.id)].slice(0,100);await api.saveReaderState(user.id,state.bookmarks,history).catch(()=>{})}};return api.getReactions(article.id,user?.id).then(x=>{setReactionCounts(x.counts);setReactionValue(x.current)}).catch(()=>{const local=JSON.parse(localStorage.getItem('fb-reactions')||'{}')[article.id]||{};setReactionCounts(local.counts||{});setReactionValue(local.userReaction||null)}).then(()=>api.getPoll(article.id,user?.id)).then(setPoll).catch(()=>{})}).catch(()=>{});api.getComments(article.id).then(setComments).catch(()=>setCommentState('unavailable'));queueMicrotask(()=>{try{setNotes(JSON.parse(localStorage.getItem('fb-annotations')||'{}')[article.id]||[])}catch{}});return()=>{live=false}},[article.id,article.slug,article.title,article.categories?.name,article.categories?.slug,minutes])

  useEffect(()=>{let sent=sessionStorage.getItem(`article-view:${article.id}`)==='sent';const commit=()=>{if(sent)return;sent=true;sessionStorage.setItem(`article-view:${article.id}`,'sent');api.countView(article.id).then(()=>setViews(v=>v+1)).catch(()=>{sent=false;sessionStorage.removeItem(`article-view:${article.id}`)})};const update=()=>{const el=prose.current;if(!el)return;const rect=el.getBoundingClientRect(),viewed=Math.min(el.offsetHeight,Math.max(0,innerHeight-rect.top));setProgress(Math.min(100,Math.max(0,viewed/Math.max(el.offsetHeight,1)*100)));if(viewed/el.offsetHeight>=.35)commit()};const timer=setTimeout(commit,12000);addEventListener('scroll',update,{passive:true});addEventListener('resize',update);update();return()=>{clearTimeout(timer);removeEventListener('scroll',update);removeEventListener('resize',update)}},[article.id])

  useEffect(()=>{const nodes=Array.from(prose.current?.querySelectorAll('h1,h2,h3')||[]);const list=nodes.map((el,index)=>{if(!el.id)el.id=`sezione-${index+1}`;return{id:el.id,text:tocLabel(el),level:Number(el.tagName[1])}}).filter(x=>x.text);queueMicrotask(()=>setHeadings(list));const observer=new IntersectionObserver(entries=>entries.forEach(e=>e.isIntersecting&&setActiveHeading(e.target.id)),{rootMargin:'-20% 0% -70%'});list.forEach(x=>{const el=document.getElementById(x.id);if(el)observer.observe(el)});return()=>observer.disconnect()},[article.content])

  useEffect(()=>{const container=prose.current;if(!container)return;container.querySelectorAll('table').forEach(table=>{if(table.parentElement?.classList.contains('table-scroll'))return;const wrap=document.createElement('div');wrap.className='table-scroll';table.replaceWith(wrap);wrap.appendChild(table)})},[article.content])

  useEffect(()=>{const container=prose.current;if(!container)return;const render=()=>{const allowed=readCookieConsent()?.externalMedia===true;container.querySelectorAll<HTMLElement>('[data-external-video]').forEach(node=>{const src=node.dataset.src||'';if(!src)return;if(!allowed){delete node.dataset.ready;node.innerHTML='<p>Questo video Ã¨ ospitato da una piattaforma esterna.</p><button type="button">Gestisci consenso video</button>';node.querySelector('button')?.addEventListener('click',()=>window.dispatchEvent(new Event(COOKIE_CONSENT_EVENT)));return}if(node.dataset.ready)return;const iframe=document.createElement('iframe');iframe.src=src;iframe.title=node.dataset.title||'Video articolo';iframe.loading='lazy';iframe.allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share';iframe.allowFullscreen=true;node.replaceChildren(iframe);node.dataset.ready='true'});container.querySelectorAll<HTMLVideoElement>('video').forEach(video=>{video.controls=true;video.preload='metadata'})};render();addEventListener(`${COOKIE_CONSENT_EVENT}:changed`,render);return()=>removeEventListener(`${COOKIE_CONSENT_EVENT}:changed`,render)},[article.content])

  useEffect(()=>{if(matchMedia('(prefers-reduced-motion: reduce)').matches||!root.current)return;let context:{revert():void}|undefined,cancelled=false;Promise.all([import('gsap'),import('gsap/ScrollTrigger')]).then(([g,t])=>{if(cancelled||!root.current)return;g.gsap.registerPlugin(t.ScrollTrigger);context=g.gsap.context(()=>{g.gsap.fromTo('[data-article-enter]',{clipPath:'inset(0 0 100% 0)'},{clipPath:'inset(0 0 0% 0)',duration:.95,stagger:.07,ease:'power4.out'});g.gsap.fromTo('.article-cover img',{scale:1.06},{scale:1,ease:'none',scrollTrigger:{trigger:'.article-cover',start:'top bottom',end:'bottom top',scrub:.7}})},root)}).catch(()=>{});return()=>{cancelled=true;context?.revert()}},[])

  async function share(kind='native'){
    const base=location.href
    const withUtm=(source:string)=>{try{const u=new URL(base);u.searchParams.set('utm_source',source);u.searchParams.set('utm_medium','share');u.searchParams.set('utm_campaign','article');return u.toString()}catch{return base}}
    const title=article.title
    if(kind==='copy'){await navigator.clipboard.writeText(withUtm('copy'));setNotice('Link copiato');return}
    if(kind==='native'&&navigator.share){await navigator.share({title,url:withUtm('native')}).catch(()=>{});return}
    const url=kind==='x'?withUtm('x'):kind==='facebook'?withUtm('facebook'):withUtm('whatsapp')
    const target=kind==='x'?`https://twitter.com/intent/tweet?text=${encodeURIComponent(title)}&url=${encodeURIComponent(url)}`:kind==='facebook'?`https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(url)}`:`https://wa.me/?text=${encodeURIComponent(`${title} ${url}`)}`
    open(target,'_blank','noopener,noreferrer')
  }
  async function toggleBookmark(){if(!reader){setNotice('Accedi ad Area Bianconera per salvare lâ€™articolo');return}const state=await api.getReaderState(reader.id);const exists=state.bookmarks.some((x:any)=>x.id===article.id||x.articleId===article.id);const item={id:article.id,articleId:article.id,slug:article.slug,title:article.title,coverImage:article.cover_image,savedAt:new Date().toISOString()};await api.saveReaderState(reader.id,exists?state.bookmarks.filter((x:any)=>x.id!==article.id&&x.articleId!==article.id):[item,...state.bookmarks],state.history);setBookmarked(!exists);setNotice(exists?'Rimosso dai salvati':'Articolo salvato')}
  async function react(emoji:string){if(reader){await api.setReaction(article.id,reader.id,reaction===emoji?null:emoji);const next=await api.getReactions(article.id,reader.id);setReactionCounts(next.counts);setReactionValue(next.current);return}const all=JSON.parse(localStorage.getItem('fb-reactions')||'{}'),current=all[article.id]||{counts:{},userReaction:null},prev=current.userReaction;if(prev)current.counts[prev]=Math.max(0,(current.counts[prev]||1)-1);current.userReaction=prev===emoji?null:emoji;if(prev!==emoji)current.counts[emoji]=(current.counts[emoji]||0)+1;all[article.id]=current;localStorage.setItem('fb-reactions',JSON.stringify(all));setReactionCounts({...current.counts});setReactionValue(current.userReaction)}
  async function submitComment(e:FormEvent){e.preventDefault();setCommentState('sending');try{await api.postComment(article.id,commentForm.name.trim(),commentForm.email.trim(),commentForm.content.trim());setCommentForm(v=>({...v,content:''}));setCommentState('sent')}catch{setCommentState('error')}}
  async function castVote(optionId:string){if(!reader){setNotice('Accedi ad Area Bianconera per votare');return}if(!poll)return;await api.votePoll(poll.id,optionId,reader.id);setPoll(await api.getPoll(article.id,reader.id))}
  function captureSelection(){const value=getSelection()?.toString().trim().slice(0,300)||'';setHighlight(value);setNoteOpen(true)}
  function persistNotes(next:Note[]){const all=JSON.parse(localStorage.getItem('fb-annotations')||'{}');all[article.id]=next;localStorage.setItem('fb-annotations',JSON.stringify(all));setNotes(next)}
  function addNote(){if(!note.trim()&&!highlight)return;persistNotes([...notes,{id:String(Date.now()),highlight,note:note.trim(),createdAt:new Date().toISOString()}]);setNote('');setHighlight('');setNoteOpen(false)}
  async function subscribe(e:FormEvent){e.preventDefault();setNewsletterState('sending');setNewsletterMessage('');try{const response=await fetch('/api/newsletter',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:newsletter})});const payload=await response.json().catch(()=>({})) as {error?:string};if(!response.ok)throw new Error(payload.error||'Iscrizione non riuscita.');setNewsletter('');setNewsletterState('done');setNewsletterMessage('Iscrizione confermata. #FinoAllaFine')}catch(error){setNewsletterState('error');setNewsletterMessage(error instanceof Error?error.message:'Iscrizione non riuscita.')}}

  return <main ref={root} id="contenuto" className="article-page" data-local-motion="true">
    <div className="reading-progress" aria-hidden="true"><span style={{transform:`scaleX(${progress/100})`}}/></div>
    {notice&&<button className="article-toast" onClick={()=>setNotice('')} aria-live="polite">{notice} Ã—</button>}
    <article>
      <header className="article-header"><nav className="article-breadcrumb" aria-label="Breadcrumb"><Link href="/">Home</Link><span>/</span>{article.categories&&<><Link href={`/categoria/${article.categories.slug}`}>{article.categories.name}</Link><span>/</span></>}<span>{article.title}</span></nav><Link data-article-enter className="article-category" href={article.categories?`/categoria/${article.categories.slug}`:'/'}>{article.categories?.name||'Magazine'}</Link><h1 data-article-enter>{article.title}</h1>{article.excerpt&&<p data-article-enter className="article-dek">{article.excerpt}</p>}<div data-article-enter className="article-byline"><span>Di {article.profiles?.username?<Link href={`/autore/${authorSlug(article.profiles.username)}`}>{article.profiles.username}</Link>:'Redazione'}</span><span>{formatDate(article.published_at)}</span><span>{minutes} min di lettura</span><span>{views.toLocaleString('it-IT')} visualizzazioni</span><button onClick={toggleBookmark}>{bookmarked?'Salvato âœ“':'Salva articolo'}</button></div></header>
      {article.cover_image&&<figure className="article-cover" data-article-enter style={{viewTransitionName:`article-cover-${article.slug}`}}><img src={article.cover_image} alt={article.title}/><figcaption>{article.title}</figcaption></figure>}
      <div className="article-layout"><aside className="article-aside" aria-label="Navigazione articolo"><span>DNA / {article.categories?.name||'Magazine'}</span>{headings.length>=2&&<div className="article-toc"><button aria-expanded={tocOpen} onClick={()=>setTocOpen(!tocOpen)}>Indice {tocOpen?'âˆ’':'+'}</button>{tocOpen&&<ol>{headings.map(h=><li key={h.id} data-level={h.level}><a data-active={activeHeading===h.id} href={`#${h.id}`}>{h.text}</a></li>)}</ol>}</div>}</aside>
        <div className="article-center">{quick&&<section className="article-widget tldr"><button aria-expanded={summaryOpen} onClick={()=>setSummaryOpen(!summaryOpen)}>TL;DR â€” Riassunto rapido <span>{summaryOpen?'âˆ’':'+'}</span></button>{summaryOpen&&<p>{quick}</p>}</section>}
          {poll?.is_active&&poll.options.length>=2&&<section className="article-widget"><p className="widget-kicker">Il sondaggio del magazine</p><h2>{poll.question}</h2>{poll.options.map(o=>{const pc=poll.totalVotes?Math.round(o.votes/poll.totalVotes*100):0;return <button className="poll-option" key={o.id} disabled={!!poll.currentVote} onClick={()=>castVote(o.id)}><i style={{width:poll.currentVote?`${pc}%`:'0'}}/><span>{o.label}{poll.currentVote&&` Â· ${pc}%`}</span></button>})}<small>{poll.currentVote?`${poll.totalVotes} voti raccolti.`:'Accedi ad Area Bianconera per votare e vedere i risultati.'}</small></section>}
          <div ref={prose} className="article-prose" dangerouslySetInnerHTML={{__html:article.content||''}}/>
          <section className="article-actions"><p className="widget-kicker">Come ti sembra questo articolo?</p><div className="reaction-row">{REACTIONS.map(x=><button key={x.emoji} data-active={reaction===x.emoji} onClick={()=>react(x.emoji)} aria-label={x.label}><span>{x.emoji}</span>{reactionCounts[x.emoji]>0&&<b>{reactionCounts[x.emoji]}</b>}</button>)}</div></section>
          {tags.length>0&&<nav className="article-tags" aria-label="Tag articolo">{tags.map(tag=><Link key={tag.id} href={`/tag/${tag.slug}`}>#{tag.name}</Link>)}</nav>}
          <section className="article-explore"><p className="widget-kicker">Continua lâ€™esplorazione</p><div>{article.categories&&<Link href={`/categoria/${article.categories.slug}`}>Altre notizie in {article.categories.name}</Link>}{article.profiles?.username&&<Link href={`/autore/${authorSlug(article.profiles.username)}`}>Profilo autore: {article.profiles.username}</Link>}{tags.slice(0,3).map(tag=><Link key={tag.id} href={`/tag/${tag.slug}`}>Topic: {tag.name}</Link>)}</div></section>
          {reader&&<section className="article-notes"><div><h2>Le tue note {notes.length?`(${notes.length})`:''}</h2><button onClick={captureSelection}>Annota selezione</button><button onClick={()=>setNoteOpen(!noteOpen)}>Nuova nota</button></div>{noteOpen&&<div className="note-form">{highlight&&<blockquote>{highlight}</blockquote>}<textarea maxLength={1000} value={note} onChange={e=>setNote(e.target.value)} placeholder="Scrivi una notaâ€¦"/><button onClick={addNote}>Salva nota</button></div>}{notes.map(n=><article key={n.id}>{n.highlight&&<blockquote>{n.highlight}</blockquote>}<p>{n.note}</p><small>{formatDate(n.createdAt)}</small><button aria-label="Elimina nota" onClick={()=>persistNotes(notes.filter(x=>x.id!==n.id))}>Elimina</button></article>)}</section>}
          <div className="article-bottom-share"><Link href="/">â† Torna alla home</Link><div><button onClick={()=>share('x')}>X</button><button onClick={()=>share('facebook')}>Facebook</button><button onClick={()=>share('whatsapp')}>WhatsApp</button><button onClick={()=>share('copy')}>Copia link</button></div></div>
          <section className="article-comments"><p className="widget-kicker">La discussione</p><h2>Commenti {comments.length?`(${comments.length})`:''}</h2>{comments.map(c=><article key={c.id}><strong>{c.author_name}</strong><small>{timeAgo(c.created_at)}</small><p>{c.content}</p></article>)}{!comments.length&&commentState!=='unavailable'&&<p>Nessun commento approvato. Sii il primo.</p>}{commentState==='unavailable'?<p>I commenti non sono ancora disponibili.</p>:commentState==='sent'?<p role="status">Commento inviato: sarÃ  visibile dopo la moderazione.</p>:<form onSubmit={submitComment}><input required maxLength={80} placeholder="Nome" value={commentForm.name} onChange={e=>setCommentForm(v=>({...v,name:e.target.value}))}/><input type="email" placeholder="Email (non pubblicata)" readOnly={!!reader?.email} value={commentForm.email} onChange={e=>setCommentForm(v=>({...v,email:e.target.value}))}/><textarea required maxLength={1000} placeholder="Scrivi il tuo commentoâ€¦" value={commentForm.content} onChange={e=>setCommentForm(v=>({...v,content:e.target.value}))}/><small>{commentForm.content.length}/1000 Â· I commenti sono moderati.</small>{commentState==='error'&&<p role="alert">Invio non riuscito. Riprova.</p>}<button disabled={commentState==='sending'}>{commentState==='sending'?'Invioâ€¦':'Invia commento'}</button></form>}</section>
        </div>
        <aside className="article-share" aria-label="Azioni articolo"><button onClick={()=>share()}>Condividi â†—ï¸Ž</button><button onClick={()=>share('copy')}>Copia link</button><button onClick={toggleBookmark}>{bookmarked?'Salvato âœ“':'Salva'}</button><button onClick={()=>print()}>Stampa</button></aside></div>
    </article>
    <section className="article-discovery" aria-label="Approfondimenti editoriali">
      <div><p className="widget-kicker">Prossima partita</p>{nextMatch?<><h2>{nextMatch.home} â€” {nextMatch.away}</h2><p>{nextMatch.competition} Â· {formatDate(nextMatch.date)}</p><Link href="/calendario">Calendario completo â†’</Link></>:<p>Calendario in aggiornamento.</p>}</div>
      <div><p className="widget-kicker">Ultime notizie</p>{sidebar.latest.map(item=><Link className="discovery-story" href={`/articolo/${item.slug}`} key={item.id}><span>{item.categories?.name||'Magazine'}</span><strong>{item.title}</strong></Link>)}</div>
      <div><p className="widget-kicker">PiÃ¹ letti</p>{sidebar.mostViewed.map((item,i)=><Link className="discovery-story numbered" href={`/articolo/${item.slug}`} key={item.id}><b>{String(i+1).padStart(2,'0')}</b><strong>{item.title}</strong></Link>)}</div>
      <div><p className="widget-kicker">Categorie</p><nav className="discovery-categories">{sidebar.categories.map(cat=><Link key={cat.id} href={`/categoria/${cat.slug}`}>{cat.name}</Link>)}</nav>{rumor&&<div className="discovery-rumor"><p className="widget-kicker">Radar mercato</p><strong>{rumor.player_name}</strong><span>{rumor.direction==='in'?'In entrata':'In uscita'} Â· {rumor.status}</span><Link href="/calciomercato/tracker">Apri il tracker â†’</Link></div>}</div>
      <div className="discovery-social"><p className="widget-kicker">BianconeriHub</p><h2>#FINOALLAFINE</h2><p>Segui il magazine e partecipa alla community bianconera.</p><Link href="/community/forum">Entra nella community â†’</Link></div>
      <div className="discovery-newsletter"><p className="widget-kicker">Newsletter BianconeriHub</p><h2>Le notizie nella tua inbox.</h2>{newsletterState==='done'?<p role="status">{newsletterMessage}</p>:<form onSubmit={subscribe}><input required type="email" value={newsletter} onChange={e=>setNewsletter(e.target.value)} placeholder="tua@email.it" aria-describedby="newsletter-feedback"/><button disabled={newsletterState==='sending'}>{newsletterState==='sending'?'Iscrizioneâ€¦':'Iscriviti'}</button></form>}{newsletterMessage&&newsletterState==='error'&&<p id="newsletter-feedback" role="alert">{newsletterMessage}</p>}<small>Nessuno spam. Cancellazione in qualsiasi momento.</small></div>
    </section>
    {related.length>0&&<section className="related-section" aria-labelledby="related-title"><p className="eyebrow">Continua a leggere</p><h2 id="related-title">Articoli correlati</h2><div>{related.map(item=><article key={item.id}><Link href={`/articolo/${item.slug}`}>{item.cover_image&&<img src={item.cover_image} alt=""/>}<p>{item.categories?.name||'Magazine'}</p><h3>{item.title}</h3></Link></article>)}</div></section>}
  </main>
}
