'use client'
import { AnimatePresence, motion, useReducedMotion } from 'motion/react'
import { useMemo, useState } from 'react'
import { useRouter, useSearchParams } from 'next/navigation'
import type { EditorialVideo } from '@/lib/editorial-content'
import s from './editorial-premium.module.css'
const cats=[['highlights','Highlights'],['interviste','Interviste'],['analisi','Analisi'],['allenamenti','Allenamenti']]
function embed(v:EditorialVideo){if(v.platform==='youtube'&&v.video_id)return `https://www.youtube.com/embed/${v.video_id}?autoplay=1`;if(v.platform==='vimeo'&&v.video_id)return `https://player.vimeo.com/video/${v.video_id}?autoplay=1`;if(v.platform==='dailymotion'&&v.video_id)return `https://www.dailymotion.com/embed/video/${v.video_id}?autoplay=1`;return null}
function thumb(v:EditorialVideo){return v.thumbnail||(v.platform==='youtube'&&v.video_id?`https://img.youtube.com/vi/${v.video_id}/hqdefault.jpg`:null)}
export function EditorialVideoIsland({videos}:{videos:EditorialVideo[]}){
 const params=useSearchParams(),router=useRouter(),reduced=useReducedMotion();const [category,setCategory]=useState('');const [activeId,setActiveId]=useState(params.get('v')||'');const filtered=useMemo(()=>category?videos.filter(v=>v.category===category):videos,[videos,category]);const active=videos.find(v=>v.id===activeId)
 function play(v:EditorialVideo){setActiveId(v.id);router.replace(`/video?v=${v.id}`,{scroll:false});fetch(`${process.env.NEXT_PUBLIC_SUPABASE_URL}/rest/v1/rpc/increment_video_views`,{method:'POST',headers:{apikey:process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY||'','Content-Type':'application/json'},body:JSON.stringify({vid_id:v.id})}).catch(()=>{})}
 return <><AnimatePresence initial={false}>{active&&<motion.section className={s.premiumPlayer} aria-live="polite" initial={reduced?false:{opacity:0,y:30}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-20}} transition={{duration:.7,ease:[.32,.72,0,1]}}><div className={s.playerBezel}><div>{embed(active)?<iframe src={embed(active)!} title={active.title} allow="autoplay; fullscreen; encrypted-media; picture-in-picture" allowFullScreen/>:<video src={active.video_url||''} poster={active.thumbnail||undefined} controls autoPlay/>}</div></div><div className={s.playerCopy}><p className={s.premiumMeta}>{active.category||'Video'} / {active.views||0} visualizzazioni</p><h2>{active.title}</h2>{active.description&&<p>{active.description}</p>}<button onClick={()=>{setActiveId('');router.replace('/video',{scroll:false})}}>Chiudi <i aria-hidden="true">×</i></button></div></motion.section>}</AnimatePresence>
 <div className={s.videoFilters} aria-label="Filtra video"><span>Seleziona formato</span><div><button data-active={!category} onClick={()=>setCategory('')}>Tutti</button>{cats.map(([value,label])=><button data-active={category===value} onClick={()=>setCategory(value)} key={value}>{label}</button>)}</div></div>
 {filtered.length?<div className={s.premiumVideoGrid}>{filtered.map((v,index)=><motion.button className={index%5===0?s.videoCardFeature:s.premiumVideoCard} key={v.id} onClick={()=>play(v)} aria-label={`Riproduci ${v.title}`} layout initial={reduced?false:{opacity:0,y:30}} animate={{opacity:1,y:0}} transition={{duration:.65,delay:Math.min(index*.04,.28),ease:[.32,.72,0,1]}}><span className={s.videoBezel}><span className={s.videoCore}>{thumb(v)&&<img src={thumb(v)!} alt=""/>}<i className={s.premiumPlay} aria-hidden="true">▶</i><b>{String(index+1).padStart(2,'0')}</b></span></span><span className={s.premiumMeta}>{v.category||'Video'} / {v.views||0} visualizzazioni</span><strong>{v.title}</strong></motion.button>)}</div>:<p className={s.premiumEmpty}>Nessun video disponibile in questa categoria.</p>}</>
}
