import type { Metadata } from 'next'
import { Link } from 'next-view-transitions'
import { PublicShell } from './public-shell'
import styles from './institutional.module.css'

export type InstitutionKind = 'about'|'editorial'|'contact'|'faq'|'terms'
const values=[['Indipendenza','Un blog libero, senza vincoli editoriali. Raccontiamo la Juventus con onestà e passione.'],['Passione','Siamo tifosi e il DNA bianconero scorre nelle nostre vene.'],['Qualità','Analisi approfondite, dati, tattica. Non semplici notizie, ma contenuti di valore.'],['Comunità','BianconeriHub è la casa di chi vive il calcio con il cuore. Ogni lettore è parte della famiglia.']]
const faq=[['BianconeriHub e affiliato a Juventus FC?','No. Il blog e indipendente e non e affiliato ufficialmente a Juventus FC.'],['Posso inviare un articolo o una proposta?','Si. Puoi usare la sezione "Area Bianconera" per proporre contenuti oppure contattarci via email.'],['Come funziona la newsletter?','Puoi iscriverti con la tua email. Riceverai aggiornamenti e potrai disiscriverti in qualsiasi momento.'],['I commenti vengono pubblicati subito?','No. I commenti passano in moderazione prima della pubblicazione per mantenere la discussione leggibile e rispettosa.']]

export function InstitutionalPage({kind}:{kind:InstitutionKind}){
 const meta={about:['Chi siamo','Un blog indipendente dedicato alla Juventus e alla passione bianconera.'],editorial:['Il progetto','Un blog di tifosi che racconta la Juventus con passione e buon senso.'],contact:['Contatti','Parla con BianconeriHub'],faq:['FAQ','Domande frequenti'],terms:['Termini','Termini di utilizzo']}[kind]
 return <PublicShell><header className={styles.hero}><p className={styles.eyebrow}>{meta[0]}</p><h1>{meta[1]}</h1>{kind==='editorial'&&<p>BianconeriHub e un blog di tifosi, non una testata giornalistica. I contenuti vengono selezionati e riletti per dare una forma chiara alla passione bianconera.</p>}</header><div className={styles.content}>
 {kind==='about'&&<><section><h2>Perché esiste BianconeriHub</h2><p><strong>BianconeriHub</strong> è un blog indipendente nato dalla passione per la Juventus. Raccoglie notizie, opinioni, analisi e conversazioni pensate per chi segue ogni giorno il mondo bianconero.</p><p>Non siamo una testata giornalistica e non siamo affiliati alla Juventus F.C. Il progetto offre uno spazio informativo e di confronto creato da tifosi per altri tifosi, con attenzione alle fonti e una distinzione chiara tra fatti e opinioni.</p></section><section><h2>I nostri valori</h2><div className={styles.grid}>{values.map(([title,desc])=><div className={styles.card} key={title}><h3>{title}</h3><p>{desc}</p></div>)}</div></section><section><h2>Il progetto</h2><p>BianconeriHub cresce attraverso contenuti, idee e contributi della community. L&apos;obiettivo è costruire uno spazio autentico in cui vivere e condividere la passione bianconera.</p><a className={styles.cta} href="mailto:info@bianconerihub.com">Contattaci</a></section></>}
 {kind==='editorial'&&<><section><h2>Come lavoriamo senza fingere di essere una newsroom</h2><p>Seguiamo la Juventus ogni giorno e proviamo a trasformare quella presenza costante in contenuti ordinati, leggibili e con un minimo di filtro. Alcuni pezzi nascono sull&apos;onda della giornata, altri richiedono piu calma, ma l&apos;idea resta la stessa: pubblicare cose che avremmo voglia di leggere noi per primi.</p></section><section><h2>Le aree che seguiamo</h2><div className={styles.grid}>{[['Notizie e live',"Seguiamo l'attualita Juventus con aggiornamenti, notizie del giorno e tutto quello che merita attenzione nel flusso quotidiano bianconero."],['Analisi e approfondimenti','Quando una partita o un tema lo richiedono, ci prendiamo piu spazio per analisi, opinioni ragionate e pezzi meno veloci.'],['Community e contributi','Area Bianconera, spunti dei lettori e contributi dei tifosi: la parte piu aperta del progetto, dove la community entra davvero nel magazine.']].map(([t,d])=><div className={styles.card} key={t}><h3>{t}</h3><p>{d}</p></div>)}</div></section><section><h2>Come passano i contenuti</h2><h3>Verifica</h3><p>Prima di pubblicare cerchiamo di controllare fonti, contesto e senso generale del pezzo, senza inseguire il rumore.</p><h3>Editing</h3><p>Rileggiamo, sistemiamo e tagliamo il superfluo per mantenere una voce chiara, leggibile e coerente con il progetto.</p><h3>Onesta</h3><p>Non siamo una testata giornalistica: puntiamo a essere seri, trasparenti e utili per chi legge, da tifosi a tifosi.</p><Link className={styles.cta} href="/contatti">Contatta la redazione</Link></section></>}
 {kind==='contact'&&<div className={styles.grid}><section className={styles.card}><h2>Email</h2><p>Per segnalazioni, proposte e partnership.</p><a href="mailto:info@bianconerihub.com">info@bianconerihub.com</a></section><section className={styles.card}><h2>Tempi di risposta</h2><p>Cerchiamo di rispondere entro 2 giorni lavorativi. Per temi urgenti indica chiaramente l’oggetto del messaggio.</p></section></div>}
 {kind==='faq'&&faq.map(([q,a])=><section key={q}><h2>{q}</h2><p>{a}</p></section>)}
 {kind==='terms'&&<><section><h2>Uso dei contenuti</h2><p>I contenuti del magazine sono destinati a consultazione personale e informativa. Non e consentita la ripubblicazione integrale senza autorizzazione.</p></section><section><h2>Commenti e contributi utenti</h2><p>L’utente resta responsabile dei contenuti inviati. La redazione puo moderare, non pubblicare o rimuovere commenti e proposte non conformi.</p></section><section><h2>Limitazione di responsabilita</h2><p>Facciamo il possibile per mantenere il magazine aggiornato e corretto, ma non possiamo garantire l’assenza di errori o interruzioni del servizio.</p></section></>}
 </div></PublicShell>
}
